"use strict";(self.webpackChunkreact_book_reader_docs=self.webpackChunkreact_book_reader_docs||[]).push([[445],{94445:function(f,m,h){h.d(m,{makePDF:function(){return y}});const w=async(a,r,n)=>{const t=n*devicePixelRatio;r.documentElement.style.transform=`scale(${1/devicePixelRatio})`,r.documentElement.style.transformOrigin="top left",r.documentElement.style.setProperty("--scale-factor",t);const e=a.getViewport({scale:t}),c=document.createElement("canvas");c.height=e.height,c.width=e.width;const g=c.getContext("2d");await a.render({canvasContext:g,viewport:e}).promise,r.querySelector("#canvas").replaceChildren(r.adoptNode(c));const d=r.querySelector(".textLayer");await new pdfjsLib.TextLayer({textContentSource:await a.streamTextContent(),container:d,viewport:e}).render();for(const s of document.querySelectorAll(".hiddenCanvasElement"))Object.assign(s.style,{position:"absolute",top:"0",left:"0",width:"0",height:"0",display:"none"});const o=document.createElement("div");o.className="endOfContent",d.append(o),d.onpointerdown=()=>d.classList.add("selecting"),d.onpointerup=()=>d.classList.remove("selecting");const i=r.querySelector(".annotationLayer");await new pdfjsLib.AnnotationLayer({page:a,viewport:e,div:i}).render({annotations:await a.getAnnotations(),linkService:{goToDestination:()=>{},getDestinationHash:s=>JSON.stringify(s),addLinkAttributes:(s,l)=>s.href=l}})},u=async(a,r)=>{const n=a.getViewport({scale:1});if(r){const t=document.createElement("canvas");t.height=n.height,t.width=n.width;const e=t.getContext("2d");return await a.render({canvasContext:e,viewport:n}).promise,new Promise(c=>t.toBlob(c))}return{src:URL.createObjectURL(new Blob([`
        <!DOCTYPE html>
        <html lang="en">
        <meta charset="utf-8">
        <meta name="viewport" content="width=${n.width}, height=${n.height}">
        <style>
        html, body {
            margin: 0;
            padding: 0;
        }
        </style>
        <div id="canvas"></div>
        <div class="textLayer"></div>
        <div class="annotationLayer"></div>
    `],{type:"text/html"})),onZoom:({doc:t,scale:e})=>w(a,t,e)}},p=a=>({label:a.title,href:JSON.stringify(a.dest),subitems:a.items.length?a.items.map(p):null}),y=async a=>{const r=new pdfjsLib.PDFDataRangeTransport(a.size,[]);r.requestDataRange=(o,i)=>{a.slice(o,i).arrayBuffer().then(s=>{r.onDataRange(o,s)})};const n=await pdfjsLib.getDocument({range:r,cMapUrl:pdfjsPath("cmaps/"),standardFontDataUrl:pdfjsPath("standard_fonts/"),isEvalSupported:!1}).promise,t={rendition:{layout:"pre-paginated"}},{metadata:e,info:c}=await n.getMetadata()??{};t.metadata={title:e?.get("dc:title")??c?.Title,author:e?.get("dc:creator")??c?.Author,contributor:e?.get("dc:contributor"),description:e?.get("dc:description")??c?.Subject,language:e?.get("dc:language"),publisher:e?.get("dc:publisher"),subject:e?.get("dc:subject"),identifier:e?.get("dc:identifier"),source:e?.get("dc:source"),rights:e?.get("dc:rights")};const g=await n.getOutline();t.toc=g?.map(p);const d=new Map;return t.sections=Array.from({length:n.numPages}).map((o,i)=>({id:i,load:async()=>{const s=d.get(i);if(s)return s;const l=await u(await n.getPage(i+1));return d.set(i,l),l},size:1e3})),t.isExternal=o=>/^\w+:/i.test(o),t.resolveHref=async o=>{const i=JSON.parse(o),s=typeof i=="string"?await n.getDestination(i):i;return{index:await n.getPageIndex(s[0])}},t.splitTOCHref=async o=>{const i=JSON.parse(o),s=typeof i=="string"?await n.getDestination(i):i;return[await n.getPageIndex(s[0]),null]},t.getTOCFragment=o=>o.documentElement,t.getCover=async()=>u(await n.getPage(1),!0),t.destroy=()=>n.destroy(),t}}}]);
